### ISSUE TITLE
Clarifications for README

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Argent77/A7-BanterAccelerator#2]
1) does it affect non-vanilla NPCs?, and banter packs
2) should it be installed after all other NPC mods

**Comment by Argent77** [comment]
This mod tweaks the global banter mechanism of the game engine. All NPCs (vanilla and modded) with a working banter dialog file should be automatically affected by it.

Installation order is more or less irrelevant. This mod counts as a tweak mod though, so I'd suggest to install it after NPC or content mods to reduce the chance that the banter settings are overridden by other mods.
